In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nlp-getting-started/sample_submission.csv
/kaggle/input/nlp-getting-started/train.csv
/kaggle/input/nlp-getting-started/test.csv


In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
train_df = pd.read_csv("/kaggle/input/nlp-getting-started/train.csv")
test_df = pd.read_csv("/kaggle/input/nlp-getting-started/test.csv")
print(train_df.head)
print(train_df.columns)
print(test_df.head)
print(test_df.columns)

<bound method NDFrame.head of          id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...  

In [3]:
from sklearn import feature_extraction, linear_model, model_selection, preprocessing
count_vectorizer = feature_extraction.text.CountVectorizer()
example_train_vectors = count_vectorizer.fit_transform(train_df["text"][0:5])
print(example_train_vectors.shape)
print(example_train_vectors)
## we use .todense() here because these vectors are "sparse" (only non-zero elements are kept to save space)
print("First document:", train_df.text[0])
print("First tweet data out the first 5:", example_train_vectors[0].todense().shape, "here 54 is the no of distinct words found across the 5 documents") 
print(example_train_vectors[0].todense(),  example_train_vectors[0].todense().sum())
print("Second document:", train_df.text[1])
print("Second tweet data out the first 5:", example_train_vectors[1].todense().shape, "here 54 is the no of distinct words found across the 5 documents")
print(example_train_vectors[1].todense(), example_train_vectors[1].todense().sum())
print("Third document:", train_df.text[2])
print("Third tweet data out the first 5:", example_train_vectors[2].todense().shape, "here 54 is the no of distinct words found across the 5 documents")
print(example_train_vectors[2].todense(),  example_train_vectors[2].todense().sum())
print("Fourth document:", train_df.text[3])
print("Fourth tweet data out the first 5:", example_train_vectors[3].todense().shape, "here 54 is the no of distinct words found across the 5 documents")
print(example_train_vectors[3].todense(),  example_train_vectors[3].todense().sum())
print("Fifth document:", train_df.text[4])
print("Fifth tweet data out the first 5:", example_train_vectors[4].todense().shape, "here 54 is the no of distinct words found across the 5 documents")
print(example_train_vectors[4].todense(),  example_train_vectors[4].todense().sum())

(5, 54)
  (0, 34)	1
  (0, 12)	1
  (0, 5)	1
  (0, 49)	1
  (0, 39)	1
  (0, 29)	1
  (0, 50)	1
  (0, 13)	1
  (0, 25)	1
  (0, 4)	1
  (0, 18)	1
  (0, 52)	1
  (0, 3)	1
  (1, 17)	1
  (1, 16)	1
  (1, 26)	1
  (1, 24)	1
  (1, 42)	1
  (1, 44)	1
  (1, 11)	1
  (2, 5)	2
  (2, 3)	1
  (2, 41)	1
  (2, 7)	1
  (2, 51)	1
  :	:
  (2, 32)	1
  (2, 15)	1
  (3, 21)	1
  (3, 14)	1
  (3, 32)	1
  (3, 1)	1
  (3, 0)	1
  (3, 35)	1
  (3, 40)	1
  (3, 53)	1
  (3, 10)	1
  (4, 50)	1
  (4, 53)	1
  (4, 23)	1
  (4, 20)	1
  (4, 46)	1
  (4, 36)	1
  (4, 19)	2
  (4, 43)	1
  (4, 2)	1
  (4, 6)	1
  (4, 48)	1
  (4, 38)	1
  (4, 22)	1
  (4, 45)	1
First document: Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all
First tweet data out the first 5: (1, 54) here 54 is the no of distinct words found across the 5 documents
[[0 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0]] 13
Second document: Forest fire near La Ronge Sask. Canada
Second tweet data out the firs

In [4]:
train_vectors = count_vectorizer.fit_transform(train_df["text"])

## note that we're NOT using .fit_transform() here. Using just .transform() makes sure
# that the tokens in the train vectors are the only ones mapped to the test vectors - 
# i.e. that the train and test vectors use the same set of tokens.
test_vectors = count_vectorizer.transform(test_df["text"])
print(train_vectors.shape)
print(train_vectors)
print("-------------------------------------------")
print(test_vectors)
print(test_vectors.shape)

(7613, 21637)
  (0, 14003)	1
  (0, 5490)	1
  (0, 2192)	1
  (0, 18669)	1
  (0, 15678)	1
  (0, 13681)	1
  (0, 18777)	1
  (0, 6379)	1
  (0, 12141)	1
  (0, 1852)	1
  (0, 7661)	1
  (0, 19774)	1
  (0, 1851)	1
  (1, 7652)	1
  (1, 7439)	1
  (1, 13122)	1
  (1, 11091)	1
  (1, 16266)	1
  (1, 16611)	1
  (1, 3843)	1
  (2, 2192)	2
  (2, 1851)	1
  (2, 15940)	1
  (2, 2312)	1
  (2, 18971)	1
  :	:
  (7611, 11518)	1
  (7611, 16895)	1
  (7611, 1670)	1
  (7611, 9967)	1
  (7611, 18814)	1
  (7611, 13361)	1
  (7611, 3047)	2
  (7611, 4589)	1
  (7611, 14783)	1
  (7611, 18088)	1
  (7611, 9841)	1
  (7612, 18669)	1
  (7612, 3698)	1
  (7612, 3797)	1
  (7612, 9304)	1
  (7612, 4517)	1
  (7612, 13195)	1
  (7612, 12698)	1
  (7612, 11187)	1
  (7612, 13391)	1
  (7612, 1434)	1
  (7612, 20606)	1
  (7612, 9170)	1
  (7612, 15606)	1
  (7612, 21262)	1
-------------------------------------------
  (0, 3904)	1
  (0, 4977)	1
  (0, 8753)	1
  (0, 10550)	1
  (0, 18591)	1
  (1, 1464)	1
  (1, 4357)	1
  (1, 5783)	1
  (1, 6379)	1
  (1, 

In [5]:
## Our vectors are really big, so we want to push our model's weights
## toward 0 without completely discounting different words - ridge regression 
## is a good way to do this.
clf = linear_model.RidgeClassifier()
from sklearn.linear_model import LogisticRegression
clf_1 = LogisticRegression(C=1.0)
from sklearn.naive_bayes import MultinomialNB
clf_2 = MultinomialNB()
from sklearn.svm import SVC
clf_3 = SVC(C=1.0, probability=True)
import xgboost as xgb
clf_4 = xgb.XGBClassifier(max_depth=7, n_estimators=200, colsample_bytree=0.8, 
                        subsample=0.8, nthread=10, learning_rate=0.1)

In [6]:
scores = model_selection.cross_val_score(clf, train_vectors, train_df["target"], cv=3, scoring="f1")
scores

array([0.59453669, 0.5642787 , 0.64082434])

In [7]:
scores = model_selection.cross_val_score(clf_1, train_vectors, train_df["target"], cv=3, scoring="f1")
scores

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.6387547 , 0.61347869, 0.68350669])

In [8]:
scores = model_selection.cross_val_score(clf_2, train_vectors, train_df["target"], cv=3, scoring="f1")
scores

array([0.66763006, 0.6557971 , 0.72431507])

In [9]:
from sklearn import decomposition
svd = decomposition.TruncatedSVD(n_components = 120)
svd.fit(train_vectors)
train_svd = svd.transform(train_vectors)

scl = preprocessing.StandardScaler()
scl.fit(train_svd)
train_svd_scl = scl.transform(train_svd)

scores = model_selection.cross_val_score(clf_3, train_svd_scl, train_df["target"], cv=3, scoring="f1")
scores

array([0.6012843 , 0.54524362, 0.60536398])

In [10]:
scores = model_selection.cross_val_score(clf_4, train_vectors, train_df["target"], cv=3, scoring="f1")
scores

array([0.59199071, 0.54358419, 0.5979926 ])

In [11]:
clf_1.fit(train_vectors, train_df["target"])

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
sample_submission = pd.read_csv("/kaggle/input/nlp-getting-started/sample_submission.csv")

In [13]:
sample_submission["target"] = clf_1.predict(test_vectors)

In [14]:
sample_submission.head()

id  target
0   0       1
1   2       1
2   3       1
3   9       0
4  11       1

In [15]:
sample_submission.to_csv("submission.csv", index=False)